@startuml

left to right direction

Utilizatorul --> (se afiseaza o lista cu operatori de comparatie JS) : selecteaza optiunea \n AlegeOperator
Utilizatorul --> (operatorul selectat \n va fi memorat) : selecteaza \n un operator

Utilizatorul --> (optiunea va permite utilizatorului \n introducerea unui set de 10 numere) : selecteaza optiunea \n InputTablou
Utilizatorul --> (setul de numere \n vor fi memorate) : introduce \n un set de numere

Utilizatorul --> (se va afisa un element de input) : selecteaza \n StabilesteReferinta
Utilizatorul --> (valoarea de referinta \n va fi memorata) : introduce \n o valoare de referinta

Utilizatorul --> (în setul de numere introdus de utilizator \n se vor caută numerele care corespund condiției stabilite de utilizator \n prin selecția operatorului și a valorii de referinta) : apasa butonul \n CautaReferinta
(în setul de numere introdus de utilizator \n se vor caută numerele care corespund condiției stabilite de utilizator \n prin selecția operatorului și a valorii de referinta) --> (se afișeaza elementele găsite)
(în setul de numere introdus de utilizator \n se vor caută numerele care corespund condiției stabilite de utilizator \n prin selecția operatorului și a valorii de referinta) --> (se afișeaza un mesaj de eroare \n în cazul în care nu exista elemente găsite)

Utilizatorul --> (opțiunile din meniu se initializeaza \n la valorile inițiale - default) : apasa butonul \n Reset

@enduml